# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import my_service_pb2 as my__service__pb2


class ItemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateItem = channel.unary_unary(
                '/myservice.ItemService/CreateItem',
                request_serializer=my__service__pb2.Item.SerializeToString,
                response_deserializer=my__service__pb2.Item.FromString,
                )
        self.GetItem = channel.unary_unary(
                '/myservice.ItemService/GetItem',
                request_serializer=my__service__pb2.ItemId.SerializeToString,
                response_deserializer=my__service__pb2.Item.FromString,
                )
        self.UpdateItem = channel.unary_unary(
                '/myservice.ItemService/UpdateItem',
                request_serializer=my__service__pb2.Item.SerializeToString,
                response_deserializer=my__service__pb2.Item.FromString,
                )
        self.DeleteItem = channel.unary_unary(
                '/myservice.ItemService/DeleteItem',
                request_serializer=my__service__pb2.ItemId.SerializeToString,
                response_deserializer=my__service__pb2.Item.FromString,
                )


class ItemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateItem(self, request, context):
        """Create an item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Retrieve an item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Update an item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Delete an item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=my__service__pb2.Item.FromString,
                    response_serializer=my__service__pb2.Item.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=my__service__pb2.ItemId.FromString,
                    response_serializer=my__service__pb2.Item.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=my__service__pb2.Item.FromString,
                    response_serializer=my__service__pb2.Item.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=my__service__pb2.ItemId.FromString,
                    response_serializer=my__service__pb2.Item.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myservice.ItemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ItemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myservice.ItemService/CreateItem',
            my__service__pb2.Item.SerializeToString,
            my__service__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myservice.ItemService/GetItem',
            my__service__pb2.ItemId.SerializeToString,
            my__service__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myservice.ItemService/UpdateItem',
            my__service__pb2.Item.SerializeToString,
            my__service__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myservice.ItemService/DeleteItem',
            my__service__pb2.ItemId.SerializeToString,
            my__service__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
